name = "CleanDung"
uuid = "57cc18e4-bfe9-11e8-03df-8f1cde655376"
authors = ["yakir12 <12.yakir@gmail.com>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
